//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.DataEF.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _202102051056323_DefaultCreatedDateMigration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202102051056323_DefaultCreatedDateMigration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.DataEF.Migrations.202102051056323_DefaultCreatedDateMigration", typeof(_202102051056323_DefaultCreatedDateMigration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAO1c224bNxB9L9B/WOxj4WglB0ETQ0rgyHZgNL7AcoK+BdQuJRPlcpUl17VQ9Mv60E/qL3SovZPcm26xAcEvEsm5cHhmyCFH/u+ff4cfnnxqPeKQk4CN7EGvb1uYuYFH2HxkR2L26q394f3PPw3PPf/J+pqOey3HASXjI/tBiMWJ43D3AfuI93zihgEPZqLnBr6DvMA57vffOYOBg4GFDbwsa3gXMUF8vPoCX8cBc/FCRIheBR6mPGmHnsmKq3WNfMwXyMUj+wwJdH7RO5sCkcBPwrZOKUGgxwTTmW0hxgKBBGh58oXjiQgDNp8soAHR++UCw7gZohwn2p/kw9tOpH8sJ+LkhCkrN+Ii8DsyHLxOLOOo5GvZ184sB7Y7BxuLpZz1yn4jexz4C8SWcbttqRJPxjSUo0f2agTBvFeiOLLS9qMMCQAY+XdkjSMqohCPGI5EiOiRdRtNKXF/w8v74A/MRiyitKgd6Ad9pQZoug2DBQ7F8g7P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
