//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.DataEF.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _202102050940403_InitialCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202102050940403_InitialCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.DataEF.Migrations.202102050940403_InitialCreate", typeof(_202102050940403_InitialCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAO1c224bNxB9L9B/WOxj4WptB0ETQ0rgyHZgNL7AcoK+BdQuJRPlcjdLrmuh6Jf1oZ/UX+hQeye5N0mW7VTwi8TLcDg8c8ghR/7373+G7x98at3jiJOAjeyDwb5tYeYGHmHzkR2L2c9v7PfvfvxheOr5D9aXrN0r2Q56Mj6y74QIjxyHu3fYR3zgEzcKeDATAzfwHeQFzuH+/lvn4MDBIMIGWZY1vImZID5efoGv44C5OBQxoheBhylPy6FmspRqXSIf8xC5eGSfIIFOzwYnU+gk8IOwrWNKEOgxwXRmW4ixQCABWh595ngiooDNJyETransportManager.UIHq7CDG0myHKcar9UdG860T2D+VEnKJjJsqNuQj8ngIPXqWWcdTuK9nXzi0HtjsFG4uFnPXSfiN7HPghYouk3LbUEY/GNJKtR/ayBcF8UOmxZ2XlezkSADDyb88ax1TEER4xHIsI0T3rOp5S4v6KF7fB75iNWExpWTv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
