//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrUpdateCompany.
        /// </summary>
        internal static string Operation_AddOrUpdateCompany {
            get {
                return ResourceManager.GetString("Operation_AddOrUpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrUpdateDriver.
        /// </summary>
        internal static string Operation_AddOrUpdateDriver {
            get {
                return ResourceManager.GetString("Operation_AddOrUpdateDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrUpdateUser.
        /// </summary>
        internal static string Operation_AddOrUpdateUser {
            get {
                return ResourceManager.GetString("Operation_AddOrUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrUpdateVehicle.
        /// </summary>
        internal static string Operation_AddOrUpdateVehicle {
            get {
                return ResourceManager.GetString("Operation_AddOrUpdateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteCompanyByCompanyId.
        /// </summary>
        internal static string Operation_DeleteCompanyByCompanyId {
            get {
                return ResourceManager.GetString("Operation_DeleteCompanyByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDriver.
        /// </summary>
        internal static string Operation_DeleteDriver {
            get {
                return ResourceManager.GetString("Operation_DeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteUser.
        /// </summary>
        internal static string Operation_DeleteUser {
            get {
                return ResourceManager.GetString("Operation_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteVehicle.
        /// </summary>
        internal static string Operation_DeleteVehicle {
            get {
                return ResourceManager.GetString("Operation_DeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllCompanies.
        /// </summary>
        internal static string Operation_GetAllCompanies {
            get {
                return ResourceManager.GetString("Operation_GetAllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllDrivers.
        /// </summary>
        internal static string Operation_GetAllDrivers {
            get {
                return ResourceManager.GetString("Operation_GetAllDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUsers.
        /// </summary>
        internal static string Operation_GetAllUsers {
            get {
                return ResourceManager.GetString("Operation_GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllVehicles.
        /// </summary>
        internal static string Operation_GetAllVehicles {
            get {
                return ResourceManager.GetString("Operation_GetAllVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCompanyByCompanyId.
        /// </summary>
        internal static string Operation_GetCompanyByCompanyId {
            get {
                return ResourceManager.GetString("Operation_GetCompanyByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDriver.
        /// </summary>
        internal static string Operation_GetDriver {
            get {
                return ResourceManager.GetString("Operation_GetDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetManyDriversByCompanyId.
        /// </summary>
        internal static string Operation_GetManyDriversByCompanyId {
            get {
                return ResourceManager.GetString("Operation_GetManyDriversByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetManyVehicleByCompanyId.
        /// </summary>
        internal static string Operation_GetManyVehicleByCompanyId {
            get {
                return ResourceManager.GetString("Operation_GetManyVehicleByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetManyVehicleByDriverId.
        /// </summary>
        internal static string Operation_GetManyVehicleByDriverId {
            get {
                return ResourceManager.GetString("Operation_GetManyVehicleByDriverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserByLogin.
        /// </summary>
        internal static string Operation_GetUserByLogin {
            get {
                return ResourceManager.GetString("Operation_GetUserByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVehicle.
        /// </summary>
        internal static string Operation_GetVehicle {
            get {
                return ResourceManager.GetString("Operation_GetVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveCompanyByCompanyId.
        /// </summary>
        internal static string Operation_RemoveCompanyByCompanyId {
            get {
                return ResourceManager.GetString("Operation_RemoveCompanyByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveDriver.
        /// </summary>
        internal static string Operation_RemoveDriver {
            get {
                return ResourceManager.GetString("Operation_RemoveDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveUser.
        /// </summary>
        internal static string Operation_RemoveUser {
            get {
                return ResourceManager.GetString("Operation_RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveVehicle.
        /// </summary>
        internal static string Operation_RemoveVehicle {
            get {
                return ResourceManager.GetString("Operation_RemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Status_Fail {
            get {
                return ResourceManager.GetString("Status_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Status_NotFound {
            get {
                return ResourceManager.GetString("Status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Status_Success {
            get {
                return ResourceManager.GetString("Status_Success", resourceCulture);
            }
        }
    }
}
