//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id компании должен быть в диапазоне от 1 до 999999.
        /// </summary>
        internal static string Error_CompanyIdOutOfRange {
            get {
                return ResourceManager.GetString("Error_CompanyIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании должно содержать не более 50 символов.
        /// </summary>
        internal static string Error_CompanyNameIsLonger {
            get {
                return ResourceManager.GetString("Error_CompanyNameIsLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно содержать не более 50 символов.
        /// </summary>
        internal static string Error_DriverNameIsLonger {
            get {
                return ResourceManager.GetString("Error_DriverNameIsLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гос. номер должен быть в формате А000АА00, где А - буквы (кириллица), а 0 - цифры.
        /// </summary>
        internal static string Error_IncorrectGovernmentNumber {
            get {
                return ResourceManager.GetString("Error_IncorrectGovernmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты мудак.
        /// </summary>
        internal static string Error_IncorrectType {
            get {
                return ResourceManager.GetString("Error_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин должен содержать не более 15 латинских букв (цифры и спецсимволы - не допускаются).
        /// </summary>
        internal static string Error_IncorrectUserLogin {
            get {
                return ResourceManager.GetString("Error_IncorrectUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать не более 20 латинских букв и цифр, среди которых, как минимум, 1 заглавная буква и 1 цифра (спецсимволы - не допускаются).
        /// </summary>
        internal static string Error_IncorrectUserPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название модели должно содержать не более 20 символов.
        /// </summary>
        internal static string Error_VehicleModelIsLonger {
            get {
                return ResourceManager.GetString("Error_VehicleModelIsLonger", resourceCulture);
            }
        }
    }
}
